### ISSUE TITLE
Tag API should only return hot tags

### ISSUE THREAD

**Issue by singularity-s0** [OpenTreeHole/backend#137]
List tags API should return top 300 tags(sorted by temperature) and tags created in the last 7 days. (the numbers can be adjusted if needed)

Justification: current list tags API returns over 7000 tags, significantly increasing loading time for frontend. We should only return tags that matter.

**Comment by singularity-s0** [comment]
The Swift app team currently agrees to this change. @w568w do you object?

**Comment by w568w** [comment]
I personally don't have a strong opinion on this, but this seems invalid to me as a single change request. Here are some of other problems need to be discussed first to avoid breaking functionality:

1. Do we need to keep the API's ability to return all tags for other use case?
2. Do we need to add an API for searching tags? (Originally, tag searching was implemented locally)
3. The search interface logic on the Flutter side needed lots of refactoring. We hadn't considered the fact that the app might have to constantly query the server when the user is entering a search term, and if we simply removed the feature that suggests a tag during a search, it could be confusing for users. **Long story short, the Flutter side may take a little longer to accomplish the adjustment.**
4. If the answer to point 1 and 2 is *yes*, I think the issue title should be rephrased as "Tag API should ***be able to*** return hot tags", not "***only***".

**Comment by singularity-s0** [comment]
This is more of a "concept" change than an API change. The proposal is basically saying that old tags used by very few people should not "qualify" as tags. They should not show up in search or all tags list.

If the user still wishes to use the tag, he can type it manually. And the backend will still merge it with the existing tag and increase its temperature.

**Comment by w568w** [comment]
I do not get the point why you want to separate those unpopular tags from "qualified" tags. 

This is a very subjective concept. And it's exactly because these tags are rare that I think it's necessary to show them: otherwise we might have more and more long-tail tags. Imagine the following scenario:

Someone created the "复旦BBS" tag a long time ago. And today, another guy decides to create a new related post. He enters "复旦"：nothing shows up because "复旦BBS" is unpopular. He then casually typed in "复旦论坛" as his tag. 

Then, here come "校内论坛", "BBS", "日月光华", "复旦日月光华", etc. Because everyone has no way of knowing that similar tags ever existed here, simply because those ones weren't popular enough to be in the top 500!

> This is more of a "concept" change than an API change.

But we need to work out a clear API change because we're playing with code, not concepts.

**Comment by singularity-s0** [comment]
That is why the API will return both **hot** tags and **recently created** tags. A new tag is given 7 days to gain popularity, if it gets to top 300, it stays. Otherwise it shall perish.

**Comment by w568w** [comment]
You should have read my comment more carefully.

> That is why the API will return both hot tags and recently created tags

The scenario I came up with ***is*** about a tag created **a long time ago**;

> Otherwise it shall perish.

1. Why? You gave no reason but an assertion. How "(loading all tags)significantly increasing loading time for frontend" comes to "(all unpopular tags) shall perish"? It is a solution, but it is not the ***only*** solution. I think you are ignoring my suggestions without giving any new point;
2. How? Delete those tags from database? Then the old posts will be incomplete; let all those tags stay in the database and stay invisible to users? Then the long-tail problem I was talking about is not resolved at all.

**Comment by singularity-s0** [comment]
If a tag's mission is to categorize posts, then old and unpopular tags have already failed in this regard. The chance that old and unpopular tags provide good categorization is minimal.

The tags will remain in database and show in posts that use them. Just not returned in the "list all tags" API. Or we could create a new API instead of replacing the existing one.

What better solution do you propose?

**Comment by w568w** [comment]
> If a tag's mission is to categorize posts, then old and unpopular tags have already failed in this regard. The chance that old and unpopular tags provide good categorization is minimal.

So your reasons are:

1. they significantly increasing loading time;
2. they can hardly provide good categorization.

Then I'd like to argue that **the 2nd reason does not lead to the conclusion "Tag API should only return hot tags". In fact, it leads to the reverse direction.** Think about it:

1. Now: posts on hot topics can find their tags; posts on cold topics can find their tags. -> The total number of tags keeps constant (assuming no new topics come up;
2. If removed: posts on hot topics can easier find their tags; posts on cold topics cannot find their tags and have to create a new one. The total number of tags keeps constant. -> The total number of tags increases.

So if your **only goal is to provide more accurate categorization, it is sane to keep as many tags as possible, or even manually create some tags that aren't already mentioned** (so that users don't create different tags that mean the same thing on their own).

> Or we could create a new API instead of replacing the existing one.

This is what I proposed in my very first comment. You indeed read it, didn't you?

**Comment by singularity-s0** [comment]
> This is what I proposed in my very first comment. You indeed read it, didn't you?

Ok then, but does the old API still have a use case? If not, we should replace the old API because it benefits older app versions as well.

**Comment by w568w** [comment]
> does the old API still have a use case?

Yes and no. At least there should be an API for searching all tags.

**Comment by singularity-s0** [comment]
> > does the old API still have a use case?
> 
> 
> 
> Yes and no. At least there should be an API for searching all tags.

In this case, we should replace the old API and create a new API that does the job of the old API. This way, older app versions can benefit from this change.
